development:
  adapter: redis
  url: redis://192.168.1.174:6379/1
  # url: redis://10.25.1.252:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:953ac5e10f3ab7599ad8148da25daf77@viperfish.redistogo.com:11658/
